### ISSUE TITLE
support for openshift v3

### ISSUE THREAD

**Issue by SeanPlusPlus** [openshift-quickstart/flask-example#14]
hiya there!

are there plans to update this repo (or create a new one) with support for os v3?

**Comment by bparees** [comment]
no immediate plans, our current python example for v3 is django based and resides here: https://github.com/openshift/django-ex

**Comment by GoelBiju** [comment]
This repository is already perfect for quick setup and use with python 2.6/2.7.

**Comment by jmtd** [comment]
> Deploying same on OS NextGen causes Crash loop back off error

confirmed (with openshift v3.6.173.0.49)

**Comment by bparees** [comment]
there are still v2 clusters out there somewhere that users may want to use this with.  i've updated a readme to add a warning at the top.
